apiVersion: v1
kind: Service
metadata:
  name: {{ include "opa.fullname" . }}
  labels:
    {{- include "opa.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  {{- if .Values.service.extraPorts }}
  {{ toYaml .Values.service.extraPorts | indent 2}}
  {{- end }}
  selector:
    {{- include "opa.selectorLabels" . | nindent 4 }}
