{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opa.serviceAccountName" .}}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{ toYaml . }}
  {{- end }}
  labels:
    app: {{ template "opa.fullname" . }}
    chart: {{ template "opa.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "opa.serviceAccountName" .}}-kubernetes-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opa.serviceAccountName" .}}-kubernetes-api
  annotations:
    kubernetes.io/service-account.name: {{ template "opa.serviceAccountName" .}}-kubernetes-api
type: kubernetes.io/service-account-token
{{- end }}
